# Environment Variables Required:
# VITE_SUPABASE_URL - Supabase project URL
# VITE_SUPABASE_ANON_KEY - Supabase anonymous key  
# VITE_GEMINI_API_KEY - Google Gemini API key
# VITE_SEARCH_API_KEY - Google Search API key
# VITE_SERP_API_KEY - SERP API key
# VITE_OPENLENS_API_URL - OpenLens Cloud Run service URL (https://snapalyze-openlens-156064765830.us-central1.run.app)

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
