[build]
builder = "dockerfile"

[deploy]
startCommand = "sh -c 'uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}'"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[env]
PORT = { default = "8000" }
PYTHONPATH = "/app/src"
DISPLAY = ":99"
CHROME_ARGS = "--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-port=9222"
